name: kms2
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0  # Add this line
  cupertino_icons: ^1.0.2
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  provider: ^6.1.2
  shared_preferences: ^2.0.0 # Check for the latest version
  image_picker: ^1.0.8 # Add this for selecting images
  flutter_stripe: ^11.3.0
  dio: ^5.7.0
  pdf: ^3.11.1
  printing: ^5.6.0  # Add this for printing capabilities
  fl_chart: ^0.69.2
  http: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
  

androidx.credentials:
  credentials: 1.2.0-rc01

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/



